### ISSUE TITLE
A8 devices  may not support downgrade to iOS 12.x or earlier version

### ISSUE THREAD

**Issue by CenYunhan** [MatthewPierson/PyBoot#11]
I have tried to downgrade my iPad mini 4 to iOS 12.2 with "No key",and I got message "ERROR: Unable to receive message from FDR 0x7fc1d04089e0 (-2). 0/2 bytes"

**Comment by MatthewPierson** [comment]
How is this related to PyBoot? PyBoot is only for booting devices, not the actual downgrade

**Comment by CenYunhan** [comment]
It does't work either.
