### ISSUE TITLE
Still waiting for root device

### ISSUE THREAD

**Issue by GhostHalston** [MatthewPierson/PyBoot#24]
./pyboot.py -i iPhone6,2 12.1.2 -d disk0s1s6
How to fix "Still waiting for root device"

**Comment by MatthewPierson** [comment]
I need more info then that to help.

**Comment by GhostHalston** [comment]
![9F018683-79B5-4096-8330-F39D3ED8FCCC](https://user-images.githubusercontent.com/35201063/82007623-f76c6f80-966a-11ea-827f-ff5c47f892d0.jpeg)

**Comment by MatthewPierson** [comment]
Have you properly dualbooted the device? I can't help you with the dualbooting process, only the actual booting that PyBoot does so please ensure that you have done the dualbooting process correctly.

**Comment by GhostHalston** [comment]
ok thanks
