### ISSUE TITLE
Failed to get RootFS name

### ISSUE THREAD

**Issue by zunda-pixel** [MatthewPierson/PyBoot#36]
## Device
iPhone 6s iOS 13.5
Second OS iOS 13.3

## Code
python3 pyboot.py -i iPhone8,1 13.3 -d disk0s1s6

## Error
Failed to get RootFS name
Please look up the RootFS filename on the key page for iPhone8,1 - iOS 13.3 theiphonewiki and type it here then press enter:

### Screenshot PC
<img width="400" alt="スクリーンショット 2020-06-04 17 37 46" src="https://user-images.githubusercontent.com/47569369/83734558-21251f00-a68a-11ea-8d90-d1d12d0263e3.png">

### Screenshot iPhone
<img width ="300" src="https://user-images.githubusercontent.com/47569369/83725877-a229e980-a67d-11ea-8d9a-9f3767e77d1c.jpg">

**Comment by jonathanware** [comment]
I found mine by going to [this page]:(https://www.theiphonewiki.com/wiki/Firmware/iPhone/13.x) finding my phone (iPhone 8,1 in your case) and version (13.3 in your case) and then clicking on the link in the "Keys" column. (The actual text you will click on will be "iPhone 8,1") [Here's your direct link](https://www.theiphonewiki.com/wiki/YukonC_17C54_(iPhone8,1)) Then the RootFS name you want is under "Root Filesystem" at the top. it'll be a .dmg. In your case it's 
038-02801-069.dmg

**Comment by zunda-pixel** [comment]
Thanks I fix this problem.
But new issue...
