### ISSUE TITLE
Iphone 7 9,3 errors even specifying firmware offline.

### ISSUE THREAD

**Issue by zamboni33** [MatthewPierson/PyBoot#50]
I have worked through as many errors as I could using the previous submission information but I am at a standstill now.

Here is my log output after patching a few firmware file paths manually:
mercia@iMac PyBoot % ./pyboot.py -i iPhone9,3 10.0.2  -q ~/Downloads/iPhone9,3_10.0.2_14A456_Restore.ipsw iPhone9,3 --debug
PyBoot - A tool for tether booting Checkm8 vulnerable iOS devices by Matty, @mosk_i
 
Current version is: Beta 0.8
User chose to use a locally stored IPSW, running some checks...
/Users/mercia/Downloads/iPhone9,3_10.0.2_14A456_Restore.ipsw is a zip archive!
Starting IPSW unzipping
IPSW found at given path...
Cleaning up old files...
Unzipping..
IPSW is for given device!
iOS version is: 10.0.2 and device model is: iPhone9,3
Checking theiphonewiki for 10.0.2 keys...
Found Keys!
Found multiple device models...
Which is your device?
 
1: d101ap
2: d10ap
 
Enter the number that corresponds with your device: 1
Device set to d101ap
Getting SHSH for signing images
Moving iBSS/iBEC...
Downloading 10.0.2's AOPFW
Downloading 10.0.2's ISP
Downloading 10.0.2's CallanFirmware
Extracting: Firmware/, from iPhone9,3_10.0.2_14A456_Restore.ipsw
ERROR: Failed to download CallanFirmware
Please re-run PyBoot again and it should work (might take a few tries)

For AOPFW and ISP I went and found the file it needed and copied it where the script is looking. I am not sure what file the CallanFirmware tag represents.

Any input is appreciated.

**Comment by zamboni33** [comment]
Im thinking things are just getting replaced or renamed at some point in the python script. I'll track through it and see if I can get things working and update.

**Comment by NotHereForTheDong** [comment]
iOS 10 doesn’t have callan firmware. Just NOP it out of the PyBoot.py or img4.py

@zamboni33

**Comment by zamboni33** [comment]
Ok so SHSH blobs are still an issue if you are trying to downgrade? 

I have two Iphone 7's where one has been upgraded and the other is still on 10.x. I assuming there is no way to downgrade the one though even if we swap out files. Is that correct?

**Comment by NotHereForTheDong** [comment]
It has nothing to do with SHSH but the SEP firmware installed on the main OS. SEP of 13.x won’t load a 10.x operating system. It’s as simple as that. This was mentioned in the release post of Divise and multiple times throughout the dualboot process.

**Comment by zamboni33** [comment]
Thank you for the clarification. I can't seem to find those release notes and I am hardly up to date on iOS knowledge. For the time being I will keep my eyes on the recent Pangu presentations and news releases to see if any work is being done with the SEP vulnerability.
