### ISSUE TITLE
usb.core.NoBackendError: No backend available

### ISSUE THREAD

**Issue by CE1CECL** [MatthewPierson/PyBoot#51]
[log.txt](https://github.com/MatthewPierson/PyBoot/files/5023212/log.txt)
Running on Mac OS Catalina, think its related to libusb, in VM (however, i use checkm8 on a rpi4) I don't know what else to say right now. Here is the full log:

**Comment by iandwelker** [comment]
try running `brew install libusb` and see if that fixes it &mdash; that seemed to fix it in #39

**Comment by valdu02100** [comment]
This command fix the problem, thanks ;)
